apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      # k8s-dev chứa những config dưới local
      # skaffold chạy dưới local nên sẽ tracking folder k8s-dev
      # hiện tại k8s-dev chứa config của ingress-ngix, bao gồm host khi chạy dưới local
      # trên github, ta sẽ sử dụng k8s-prod, vì lúc này ingress-ngix sẽ dùng host của prod
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticket-dev-292608
  artifacts:
    # - image: us.gcr.io/ticket-dev-292608/auth
    - image: 171195/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: 171195/client-ticket
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: 171195/ticket
      context: ticket
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: 171195/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: 171195/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: 171195/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
