name: deploy-manifests

on:
  # khi infra folder của branch master thay đổi thì thực hiện tiếp
  push:
    branches:
      - master
    paths:
      - 'infra/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # install doctl
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # connect k8s vs context
      - run: doctl kubernetes cluster kubeconfig save ticketing

      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
